### ISSUE TITLE
hamburger menu overlaid with toolbar (delete/red cross icon)

### ISSUE THREAD

**Issue by bluikko** [cxw42/TabFern#121]
If hovering over tab/window that is at bottom of tabfern list, the hamburger menu is overlaid over the toolbar's delete/red cross icon button and toolbar is unclickable.

Suggest to either move the hamburger menu to left bottom corner, or detect if toolbar is drawn under the hamburger menu and move toolbar left accordingly (leaving the hamburger menu on the right side of the toolbar).

**Comment by cxw42** [comment]
Ah!  That's exactly why you can scroll the window down farther than the last item :) .

![image](https://user-images.githubusercontent.com/10515894/38037778-925234c6-3277-11e8-8d9a-34c80b4afa96.png)

Does that work for you?

**Comment by bluikko** [comment]
OK, I see. That makes sense, I guess this can be just closed.
