### ISSUE TITLE
New Logo for TabFern

### ISSUE THREAD

**Issue by Yasujizr** [cxw42/TabFern#137]
I ran into your project while you were walking around Github. I design a logo for open source projects to do things I can put in sites like Dribbble, Behance. I can design a Logo for you if you want. What kind of Logo do you want? What are the benefits of the program? What are your favorite logo samples?

If you say these, I can design a logo for you.

**Comment by cxw42** [comment]
@Yasujizr Thank you for your interest!  I see that you have worked on [some other projects](https://steemit.com/@yasujizr) as well.  I am sure you know, but I want to be clear.  I am not able to pay. 
 However, I am happy to list you in the credits.  I would ask for a CC-BY-SA 3.0+ license.

TabFern saves and restores sets of browser tabs.  It will someday be a full tree with nesting (#34).  For now, it only stores windows and their tabs (no nesting).  It is a small tree => a fern => TabFern.

I drew the current icon in Inkscape based on a Barnsley fractal fern.  I couldn't figure out how to make an icon that represented "tab" and also "fern."  Can you think of a way?

Key features include:

 - fast open and close of tabs
 - easy backup and restore
 - making notes on tabs and windows

CC @ShervinM on #65 - ShervinM may also have some ideas.

**Comment by cxw42** [comment]
@Yasujizr I forgot to ask: do you do icons also?  I would like the favicon to be similar to the logo if possible.  I look forward to your thoughts!  Thanks again!

Separately, if you are interested in UI icon design at all, I would also be happy to talk about that.  I am currently using a mix of [Silk](http://www.famfamfam.com/lab/icons/silk/) and [Font Awesome 4](https://fontawesome.com/v4.7.0/).

**Comment by Yasujizr** [comment]
![tabfern](https://user-images.githubusercontent.com/36993664/46764650-b02b3980-cce5-11e8-9604-79a580fc69eb.jpg)


Hi, I'm sorry for the late reply. It was a little hard to combine Tab and Fern. I did Fern directly. I thought about the flowerpot format for the tab.

I'd like to do my best for the icons, but we'd better fix the logo first. I'm not very good at icon.

I don't want to pay you. It's enough to mention my name in the project. The subject of the license is also not a problem.

**Comment by Yasujizr** [comment]
I'm glad you like it. The font I use in logotypes is Mina (Bold). Waiting for your feedback.

**Comment by cxw42** [comment]
@Yasujizr I just want to let you know I haven't forgotten about this.  Thanks for your patience!

**Comment by cxw42** [comment]
@Yasujizr I appreciate your patience!  I prefer the top one.  I have thought about camel case vs. lowercase, and would like to keep the camel case.  Would you be willing to tighten up the logo and text, kern, and switch case?  Something like this (rough mockup) ---

![logo-thoughts-1](https://user-images.githubusercontent.com/10515894/48667586-80840400-ead1-11e8-9366-3caee1caa604.png)

Would you please send me an SVG or other Inkscape-readable format of the final?  Then I can use it to prepare the app icon and promotional images ([guidelines](https://developer.chrome.com/webstore/images)).  For reference, the icon is 96x96 plus padding, and the promo images are 440x280 and up.

After that, if you're willing to talk about favicon, I'd like to do so :) .  Please let me know either way.

Thank you!!!!!

**Comment by cxw42** [comment]
@Yasujizr I am just about ready to release the next version of TF (https://github.com/cxw42/TabFern/tree/switchover).  Would you have time to update the logo in the next week or two?  If so, I will wait so that the new release can include the new logo.  Please let me know either way.  Thanks!

**Comment by Yasujizr** [comment]
Hi, 

I've uploaded it to Google Drive. 98px, 128px, 280px and logotype in the file as svg. If there is a problem, type again.

https://drive.google.com/open?id=1gs2bIzqcmmE95CKG7msUZePXu01Ji8Jr

**Comment by cxw42** [comment]
Received with thanks!  I will add it in before the next release.  I appreciate your work on this!
