### ISSUE TITLE
On Mac, interaction with another extension triggers browser slowdown

### ISSUE THREAD

**Issue by vitaly-zdanevich** [cxw42/TabFern#150]
I tried to install multiple times and always right after installing I get lagging Chrome, it is almost unusable :(

**Comment by vitaly-zdanevich** [comment]
Chrome 69.0.3497.100 - current stable branch.

When not installed - Chrome works without that big lags. This lags not just "after" but always after installing this extension, it is difficult to use the browser with it, even when your window is closed.

I have no such lagging experience with any other extension.

Tried to install on new Chrome profile - the same lagging - looks like you mining bitcoins in the background :)

Installed from Chrome store.

**Comment by cxw42** [comment]
I appreciate the updates! I have not experienced that myself.  I downloaded the CRX from the Chrome Web Store and I don't see anything odd in it.

Would you please check if there are any errors in the background page?  When the TabFern window is closed, that should be all that's running.  Screenshot of steps:

![untitled](https://user-images.githubusercontent.com/10515894/46210724-0f21a380-c321-11e8-9f14-d6102d23742f.png)

If there are any errors or warnings in the console, please let me know what they are.  Thanks!

**Comment by vitaly-zdanevich** [comment]
I recorded the video about that:

https://www.youtube.com/watch?v=3yABhFsINq8

**Comment by cxw42** [comment]
Thanks for the video!  I forgot to ask you about the task manager, so I'm glad you checked that at the end.  I see what you mean about the slowdown.  Also, you may be the first Mac user :) .

 - At 0:57, is the gray screen the TabFern window?
 - At 2:29 it looks like the TF window is still open.  Is that correct?
 - The background.js output is normal, and the CPU/memory of TF at 6:10 and 6:13 also looks normal.
 - I see at 6:11 that AliExpress and the Browser process were taking up the most CPU.  That is also the case for me --- I picked [this](https://www.aliexpress.com/item/150-PSI-mini-portable-stainless-steel-Bicycle-Pumps-LED-lights-LCD-digital-display-Inflator-Multifunctional-Bicycle/32810992390.html?spm=2114.search0104.3.125.387a1ad5hJKq14&ws_ab_test=searchweb0_0,searchweb201602_5_10065_10068_204_10130_5727215_318_10547_10546_10059_10884_10548_5727315_10545_10887_10696_100031_10084_10083_10103_10618_452_10307_532,searchweb201603_60,ppcSwitch_0&algo_expid=74bf9fd9-59a8-42b1-a3e1-a02f54ca7744-16&algo_pvid=74bf9fd9-59a8-42b1-a3e1-a02f54ca7744&priceBeautifyAB=0) as a random test page.

If the TF window was still open and was blank gray, that would be very strange.  If initialization doesn't finish within 3 sec, you should see a red "Initialization not complete" message.

I am still interested in a test after a reboot, on a brand-new Chrome profile, with no other extensions or apps loaded, first with the TF window open and second with the TF window closed.  Also, while the TF window is open, please check the console to see if it has any errors or warnings reported.  You get to it the same way you get to the background page console, but choose "src/view/main.html" in the extension details.

If found [this SO question](https://superuser.com/q/776455/269989) that may be pertinent.  It led me [here](https://jasonsavard.com/forum/discussion/3967/recent-tabs-causes-bad-performance-in-google-docs), which mentions lots of errors being thrown.  That is why I am also curious about the TF window.

**Comment by vitaly-zdanevich** [comment]
Tested on clean Chromium - cannot reproduce, works as expected.

**Comment by cxw42** [comment]
OK - I am glad to hear that!  It is probably an extension incompatibility.  For example, TF and The Great Suspender don't work well together (both solve the same problem in different, mutually exclusive ways).  Are you running Great Suspender?

I would like to fix this but need your help to do so.  If you have time, would you please try the clean Chromium, with TabFern, with only one other extension at a time?  Hopefully that will tell us which extension is triggering the negative interaction.  Then I can investigate that extension and see what I find out.

**Comment by cxw42** [comment]
Having not heard anything further, I am going to close this.  If you have problems again, feel free to reopen!
