### ISSUE TITLE
Don't open TabFern in big window upon initialization

### ISSUE THREAD

**Issue by beorn** [cxw42/TabFern#169]
Whenever I open TabFern it opens a huge blank window first before shrinking down to the smaller size.  This is very disruptive and lasts a few seconds - wouldn't it be possible to open it up in a really small window first, or open up at the last size and location?

See screenshot attached.
![screenshot](https://user-images.githubusercontent.com/8559/52114019-e8b0a380-2645-11e9-8d16-b248dd82d17d.jpg)

**Comment by cxw42** [comment]
@beorn Thank you for using TF and for the feedback!  Related to #140; blocked on #35.

Short answer: yes, I certainly can!  There was a question about that somewhere (can't find it now), and the "switchover" (development) branch moves the window out of the way more quickly.  Once I have fixed #35 and rolled out the update, I'll respond here so you can see if it fixes the problem.
