### ISSUE TITLE
Feature request: cron job for exporting data

### ISSUE THREAD

**Issue by philiprhoades** [cxw42/TabFern#172]
Chris,

After recent dramas, it (re-)occurred to me that it would be nice to have a feature that automatically did an export of the TF data every day.

I realise this is more a wish list item compared to other higher-priority jobs but it is also occurred to me this morning that I could do what I wanted by making use of your extract.js set up and a normal cron job - so if a built-in enhancement is not likely for the foreseeable future, I will get that working.

Thanks again for all your help and a great app - I couldn't get by without it these days!

Regards,
Phil.

**Comment by cxw42** [comment]
Phil, TF itself doesn't have enough access to the system to run cron jobs, but you can certainly set one up as you described.  This is a design limitation of Chromium to keep extensions sandboxed.

Timed backup is open as #21, so I'm closing this one as a duplicate.

Thanks for the kind words!
