### ISSUE TITLE
After a previous problem: change from Vivaldi back to Chrome - lost TF icon again!

### ISSUE THREAD

**Issue by philiprhoades** [cxw42/TabFern#173]
Chris,

After this problem occurred (which you helped me to recover from):

https://github.com/cxw42/TabFern/issues/170

- I had assumed that the issue was from some problem with Vivaldi but now it has happened again with Chrome!

In TF I had been doing a lot of moving of tabs between windows - mostly YouTube tabs to a "YT Videos to Watch" TF window.  I had also moved a number of windows to the top and re-ordered other etc.  Fortunately I then an export but then I tried to also save the settings but I kept getting an new page with a "can't be found" error - unfortunately I didn't make a copy of that URL.  Anyway, that made me nervous so I gradually "Closed and Saved" windows from FT and then closed the FT window.  After starting Chrome again . . the TF icon was gone but at least this time I could recover quickly.

I will keep watching this problem and see if I can eventually make it reproducible . .

Phil.

**Comment by cxw42** [comment]
Phil, thanks for the heads-up.  I look forward to hearing more if you are able to figure something out.  I just now did a save/load settings cycle with no problems on my Chrome installation.

**Comment by cxw42** [comment]
@philiprhoades I'm going to close this for now.  If you have more data, feel free to re-open.  Thanks!

**Comment by philiprhoades** [comment]
@cxw42 ,

No worries - this particular issue has not been a problem again but there is another almost trivial issue with blank FT tabs being opened on my Fedora workstation but I am away again ATM and will have a closer look at it when I get back home to in a few days.

**Comment by cxw42** [comment]
@philiprhoades Thanks!  It might be #198 , which I just ran into a day or two ago.
