### ISSUE TITLE
Cannot find module "process" from "/"

### ISSUE THREAD

**Issue by cxw42** [cxw42/TabFern#179]
Forked off of #100.  The generated background.js file throws this error.

See https://github.com/cxw42/TabFern/issues/100#issuecomment-513267574 for the current workaround.

**Comment by cxw42** [comment]
@devinrhode2 Would you please try the latest commit (https://github.com/cxw42/TabFern/commit/b8ee6e4f9a55062fd72d694ef93d8bcf6488ce80) on the `issue35` branch?  I think I may have found a fix that does not require manually editing the generated source.  Please let me know if rebuilding and loading without hand-editing works for you.  Thanks!

**Comment by devinrhode2** [comment]
Hey Chris, I have upgraded from my old MacBook Air - and while I would still love to break free from chrome, I don't have much time for anything outside work right now. (The new macbook pro I have is plenty fast enough, so I don't need firefox as much as I used to)

There is A LOT that could be done with tabs outerliner/tabs fern... there could be a web app you login to and view tabs on mobile... but I unfortunately don't have the time right now and not sure when I will find the time :(

If you think you might have a working version for firefox, I'm sure someone else on the internet would love to try it. To that person - you'll need to search around to learn basics on developing a firefox addon. You'll need to know git basics. And then you might be able to try @cxw42's firefox version on the `issue35` git branch.

**Comment by cxw42** [comment]
@devinrhode2 Thanks for letting me know!  Good luck with everything at work, and I look forward to talking again whenever you get the chance :) .  Much appreciated!

**Comment by cxw42** [comment]
@devinrhode2 Wondering if you ever had a chance to try this out.  I haven't had any problems recently, so I think this can probably be closed.  Let me know your thoughts!

**Comment by devinrhode2** [comment]
Oddly enough, I have been back to using chrome. Feel free to close for now, it can always be re-opened
