### ISSUE TITLE
Update the theme of the TabFern web site

### ISSUE THREAD

**Issue by cxw42** [cxw42/TabFern#188]
If you have HTML and CSS chops, roll a new Jekyll theme for the [TabFern web site](https://cxw42.github.io/TabFern/)!  Please check it on mobile and desktop before finalizing your PR.  I am happy to try out and discuss a draft PR if you wish.

**Comment by sarthakpranesh** [comment]
Hey, I would like to help you get a new website running.
Please do let me know what are you looking for and how should I start the work ( by making a new branch or forking )

**Comment by cxw42** [comment]
Thank you!  Please fork gh-pages.  The only visual guidance I have, unfortunately, is the TF logo and font - see #137 .  @Yasujizr any suggestions?

Please leave the site content largely as it is for this issue.  It can be broken into multiple pages if you wish.

**Comment by cxw42** [comment]
Please see [updated contribution guidelines](https://github.com/cxw42/TabFern/blob/master/CONTRIBUTING.md#Legal).  Thanks!

**Comment by sarthakpranesh** [comment]
Sorry for taking too long, was taken up by some academic stuff 

I have updated the site but I wasn't able to understand the already existing environment the previous site was hosted on so I only did changes to the following folders and files:- 
 - index.html
 - assets

*for testing purpose I used the live server extension on vsCode

Also attaching a video link showing the current site ( please let me know of any changes )
https://drive.google.com/file/d/1qtq4edMutjkD9D3wbGqdBdy8BMRDL82R/view?usp=sharing
Warm regards

**Comment by cxw42** [comment]
The video looks good - the theme is nice and clean!  I would be happy to have a PR.

Development is on the `jekyll` branch.  Sorry I hadn't documented the process yet!

- Clone TF and `git checkout -b newsite origin/jekyll`.  
- Make a GitHub personal access token, e.g., following the instructions [here](https://mycyberuniverse.com/fixing-jekyll-github-metadata-warning.html).  
- Set the `JEKYLL_GITHUB_TOKEN` environment variable to the value of the new token.  E.g., on Cygwin, I have a `token.sh` that just says

      export JEKYLL_GITHUB_TOKEN=<the token>

  and I run `. token.sh` to load the environment.
- Install Jekyll
- Run `make build`.  This will build the site to `_site`.  
- Run `make test` to see the site on localhost.

When ready, commit your changes to jekyll and send the PR!  After it is merged, I will update the `gh-pages` branch (which holds the live site) by running `make deploy` and committing.

**Comment by sarthakpranesh** [comment]
Sorry for taking so long..........

I'll like to propose a non-Jekyll solution. The site is fairly simple and hence I believe it's deployment should be kept even more simple. 
I would like ZEIT solution ( https://zeit.co/ ). Deployment on ZEIT is quite simple and does not require any prior configuration. Plus no code will be required to be maintained for any deployment making the site liter and easier to maintain.
(If you say I can deploy a test version)

For now, I am opening the PR on gh-pages. Hoping to hear from you soon.

**Comment by cxw42** [comment]
@sarthakpranesh Thank you for telling me about ZEIT!  For now I will stay with GitHub pages, but I may use ZEIT in the future.
