### ISSUE TITLE
Figure out if we need to do anything with SameSite cookie settings

### ISSUE THREAD

**Issue by cxw42** [cxw42/TabFern#196]
In Chrome 77, the Errors panel in `chrome://extensions` shows warnings about non-`Secure` `SameSite` cookies.  As far as I can tell, we don't need to do anything, since we don't process cookies directly.  (It looks like these are coming in when we request the favicons for the tree.)  However, the warnings do clutter the Errors panel.  Is there anything we can or should do?

Links:

- https://www.chromestatus.com/feature/5088147346030592
- https://www.chromium.org/updates/same-site
- https://web.dev/samesite-cookies-explained
- https://www.chromestatus.com/feature/5633521622188032

**Comment by Procyon-b** [comment]
I have discovered recently, when playing with tampermonkey's settings, that chrome has a protocol for that.
Try `chrome://favicon/https://github.com/`

**Comment by cxw42** [comment]
Thanks!  I'll take a look.  Do you think we can replace all of the icon URLs in the tree?

**Comment by Procyon-b** [comment]
After some testing I know that chrome won't fetch unknown favicons, but use a placeholder.
It will display anything that it has in memory or used in a tab.

**Comment by cxw42** [comment]
OK- thanks for investigating!  That suggests to that we still need to use the regular URLs in the tree, since icons should still be valid even long after the last visit to the site.

**Comment by Procyon-b** [comment]
Tampermonkey gives the possibility to use services for .ico
I have it set to use duckduckgo. For example: `https://icons.duckduckgo.com/ip2/www.alternityrpg.net.ico`
I don't know if it is 100% efficient or not

**Comment by cxw42** [comment]
Chromium 87.0.4280.88 (Official Build) snap (64-bit) on the issue35 branch, which includes the above-noted commit, does not have the SameSite warnings.  Marking this as ready.

**Comment by cxw42** [comment]
Fixed in 0.3.0
