### ISSUE TITLE
Chrome 79: opening a tab in a partially-open windows leaves new_tab.html visible

### ISSUE THREAD

**Issue by cxw42** [cxw42/TabFern#198]
### Bug

Steps:

- Open a single tab in a saved multi-tab window
- Click to open another tab

Expected: the tab opens

Observed: a blank tab opens (and appears in the tree) showing the `chrome-extension...new_tab.html#id` URL.

**Edit** the underlying issue also prevents you from opening the Settings dialog in the currently-released version. 
### Initial observations

In Chrome 79, onTabCreated happens before the Chrome callback to chrome.tabs.create instead of after.  This didn't used to be the case.  As a result, the tab_val initialization in the callback hasn't happened when onTabCreated runs, so onTabCreated can't find the tab_val.

The Right Thing(TM) is probably to put the onTabCreated material in a seq triggered when the tabs.create completes, but I don't know for sure.

**Comment by philiprhoades** [comment]
Ah right - I did see #173 but must have skimmed it too much and not recognised it as the same issue . .

Thanks!

**Comment by cxw42** [comment]
@philiprhoades after further investigation, it looks like the problem was simpler than I realized :) .  `master` now has a barely-tested fix --- b7b2ba4.  Would you please try it and let me know how it goes?  Thanks!

**Comment by philiprhoades** [comment]
I installed the latest from the Chrome Web Store (is that the same as  8e1c3aa ?) but that does not allow me to open individual tabs . . also it seems to be duplicating tabs . .

**Comment by cxw42** [comment]
0.2.1 is 441cc92.
- The Web Store version does not have individual-tab opening --- you still have to use a dev build for that.  The code is in there, and variable `ISSUE35` in app/common/setting-definitions.js controls whether it's enabled.
- Duplicating tabs: would you please see if that sounds like #204?

**Comment by cxw42** [comment]
I've been using 0.2.1 for several days now and haven't experienced this.  Closing - let me know if you experience this specific problem (new_tab.html tabs) again.
