### ISSUE TITLE
When start chromium based browser, all windows are merged

### ISSUE THREAD

**Issue by andr222** [cxw42/TabFern#204]
tabfern version 0.2.1
1. The browser in question is closed, with no windows open
2. Tabfern is already installed, with various tabs in 2 or more windows.
3. When the browser is opened, all the various tabs appear in the same window

This occurs with Vivaldi, Chromium, and Brave.
Note that if the browser in question is open, opening a new window is according the default configured for the browser in question.  It will contain only one new tab.

I don't know how to find the file  tabfern uses to save the tabs.
Since each affected browser has a different set of tabs, it must somehow be associated with the browser used.

Note that  all tabs are put into the same window, and this time duplicated.  (Sometimes triplicated.)
The last tab used for this report was already open, so duplicated initially as well, but I navigated to a different page to open the bug report.

display of tabfern window top
![Capture du 2020-04-18 13-24-11](https://user-images.githubusercontent.com/32662304/79644639-3399d680-8178-11ea-9112-56ae3bf97dc2.png)

display of tabfern window lower
![Capture du 2020-04-18 13-25-01](https://user-images.githubusercontent.com/32662304/79644640-34326d00-8178-11ea-9a7f-48a5dd513450.png)

config of tabfern
[TabFern settings backup 2020-04-18T16.40.44.630Z.tabfern_settings.txt](https://github.com/cxw42/TabFern/files/4497050/TabFern.settings.backup.2020-04-18T16.40.44.630Z.tabfern_settings.txt)

**Comment by andr222** [comment]
Correction
With Vivaldi, not ALL the windows in tabfern were merged.
But it seems that all recently used windows were merged.
Many windows not used in the last few weeks were NOT merged.
I tend to leave the most recently used windows open under tabfern, but close most others.

So are all the windows still open when the browser is closed being merged ?

Note that the tabs are opening in a new window called 'non enregistré'.  (not registered)
All the original windows are still defined, but closed.

This is for Vivaldi, which has many hundreds of tabs defined, in about 30 windows.
However for Chromium and Brave, ALL the tabs are merged in a new window, even for windows closed when the browser was closed.
 Again, the previous windows remain defined.

A possible reason for the difference with Vivaldi, maybe the large number of open tabs defined ?
In Chromium, for example, only about 40 tabs are defined, in 3 windows.

**Comment by cxw42** [comment]
Thanks for reporting!  Would you please tell me the version information from `about:version` for each browser?

Are there any error or warning messages in TabFern's developer console?  In Chrome, click on the TF window and hit ctl+shift+i. Much appreciated!

**Comment by andr222** [comment]
For chromium : 
version  81.0.4044.92 (development build) Mageia.org 7 (64 bits)
ctl+shift+i + click on console tab
display of console page follows
--------start display
container.js:187 TabFern common.js loading
container.js:11516 TabFern: running app/win/container.js
main.js:187 TabFern common.js loading
main.js:34277 =============================================================
Loading TabFern 0.2.1 from app/win/main_tl.js
    manifest ver 0.2.1.1337
    manifest ver_name 0.2.1
main.js:34420 Issue #35 support: disabled
container.js:11581 TabFern main.js onload
container.html:1 A cookie associated with a cross-site resource at http://radio-canada.ca/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
container.html:1 A cookie associated with a cross-site resource at http://ici.radio-canada.ca/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
container.html:1 A cookie associated with a cross-site resource at https://ici.radio-canada.ca/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
DevTools failed to load SourceMap: Could not load content for chrome-extension://hbajjpcdbninabigakflkhiogmmjaakm/win/container.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://hbajjpcdbninabigakflkhiogmmjaakm/win/main.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://hbajjpcdbninabigakflkhiogmmjaakm/win/main-pre.css.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
--------end display

**Comment by andr222** [comment]
vivaldi version = 2.4.1488.40 (stable channel) (64 bits) on linux
ctl+shift+i + click console tab
-----console display start
TabFern common.js loading
container.js:11516 TabFern: running app/win/container.js
main.js:187 TabFern common.js loading
main.js:34277 =============================================================
Loading TabFern 0.2.1 from app/win/main_tl.js
    manifest ver 0.2.1.1337
    manifest ver_name 0.2.1
main.js:34420 Issue #35 support: disabled
container.js:11581 TabFern main.js onload
-------display end

**Comment by andr222** [comment]
Brave  version 1.3.118 chromium: 80.0.3987.116 (official build) (64 bit)
ctl+shift+i + click console tab
------start display
TabFern common.js loading
container.js:11516 TabFern: running app/win/container.js
main.js:187 TabFern common.js loading
main.js:34277 =============================================================
Loading TabFern 0.2.1 from app/win/main_tl.js
    manifest ver 0.2.1.1337
    manifest ver_name 0.2.1
main.js:34420 Issue #35 support: disabled
container.js:11581 TabFern main.js onload
DevTools failed to parse SourceMap: chrome-extension://hbajjpcdbninabigakflkhiogmmjaakm/win/container.js.map
DevTools failed to parse SourceMap: chrome-extension://hbajjpcdbninabigakflkhiogmmjaakm/win/main.js.map
DevTools failed to parse SourceMap: chrome-extension://hbajjpcdbninabigakflkhiogmmjaakm/win/main-pre.css.map
-------display end

**Comment by andr222** [comment]
Hope this helps.
It would be nice to know where the tab list is stored.
Or how to export it.
I would like to transit from vivaldi to brave and chromium, without losing all my tabs, if possible.  Vivaldi isn't open source, the others are.
Thanks

**Comment by cxw42** [comment]
Export is on the hamburger menu - Backup Now :) .  There is no other data stored about the tabs, and a backup file from one browser should be loadable on another (it's JSON).

Thanks for the info!  Nothing odd in the console, so I'd like to next try the standard remote-debugging questions.

- if you create a new browser profile with only TF loaded, does the problem occur?

- on your existing profile, if you disable extensions one at a time, is there one that seems to trigger the problem?

If you have any other extensions running that send messages to all open windows, the TF window might be receiving those and misinterpreting them.  

I don't know if you'd be open to a remote desktop session, but if so, that would be the fastest way for me to investigate what's going on.  Let me know what you think - if you prefer not to, no worries!  I'd like to help if I can.

(And if you know any JS developers with bandwidth, please send them my way!  I could really use some additional coding help! :) )

**Comment by andr222** [comment]
I only had one other extension in Vivaldi, and disabling it had not effect on problem.
(there were no extensions installed by default)
Disabled the several extensions in the brave (all but one installed by default), yet to test.
Disabled the several extensions active in chromium (all installed by default), yet to test.
Will complete testing soon.

**Comment by andr222** [comment]
I'm quite busy with the virus crisis.
Otherwise I would like to help with JS, but I'm far from an expert.
Also I'm not familiar with the chromium environment.

**Comment by cxw42** [comment]
Thanks for the updates and for testing!  I completely understand.

**Comment by cxw42** [comment]
By the way, do you have two versions of TF running at the same time in one browser?  E.g., the Web Store version and also a development version?  I was doing that a few minutes ago and noticed some odd behaviour.  Unfortunately, I haven't been able to reproduce it.

**Comment by andr222** [comment]
No, I have just the one (web store) version.  The same in each browser.
I've been occupied with urgent house repairs lately, as well as the various covid delays, so haven't had the time & energy to continue testing.  But intend to soon.

**Comment by cxw42** [comment]
No worries - at your convenience!  I hope everything on the house turns out OK.  Thanks for the update!

**Comment by cxw42** [comment]
@andr222 any updates?  If not, I'd like to close this issue.  You can always reopen it if you have more data later on!

**Comment by andr222** [comment]
The problem of open windows being merged used to happen regularly.
It has happened occasionally more recently, but not since nov 1 (at least).
I think that something has changed to correct this problem
- maybe in the chromium base on which other chromium family browsers are built
- maybe in Vivaldi (which is now the only browser I use regularly)
-  or maybe in tabfern itself (as a side-effect of some other change ?)
So I agree about closing the issue.

**Comment by cxw42** [comment]
@andr222 Thanks for getting back to me!  Glad it's working now :) .
