### ISSUE TITLE
Looking at Brave once again - opening "Settings and Offline Help" does not work

### ISSUE THREAD

**Issue by philiprhoades** [cxw42/TabFern#209]
People,

I periodically look at Brave to see how it is developing and although the Linux RPM version has not changed recently, I couldn't remember why I didn't keep using Brave from the last test . . there was a problem of some sort because I would like to be making more use of it . .

Anyway, I decided to have another look at it and, of course, I need TF installed for Brave to be at all useful for me as a Chrome alternative.  So far I have only one saved window with all the default settings - but when I try to change the settings, the Settings window does not display.

I am still loading TF v0.2.1-pre.1 because I need the individual tab opening facility.

Brave:

Version 1.2.42 Chromium: 79.0.3945.117 (Official Build) (64-bit)

Thanks,
Phil.

**Comment by cxw42** [comment]
It's still opening the new_tab.html pages?  0.2.1-pre.1 is fairly old - please:
- checkout `master` (3d976e9)
- edit  app/common/setting-definitions.js and change `ISSUE35 = false` at the top to `ISSUE35 = true`
- rebuild
- let me know if you still have problems.

Thanks!

**Comment by HikariWS** [comment]
I've been using Brave with 4 windows and it works great.

**Comment by cxw42** [comment]
@HikariWS thanks for the update!  Sounds like this one can be closed.
