### ISSUE TITLE
images in README.md

### ISSUE THREAD

**Issue by Procyon-b** [cxw42/TabFern#213]
The page is using https://raw.githubusercontent.com/cxw42/TabFern/gh-pages/screenshot.png
but the url is now https://raw.githubusercontent.com/cxw42/TabFern/gh-pages/assets/img/screenshot.png

Same for:
https://raw.githubusercontent.com/cxw42/TabFern/master/static/assets/fern128.png
available here:
https://raw.githubusercontent.com/cxw42/TabFern/gh-pages/assets/img/fern128.png
But not the same branch. You'll have to double-check.

**Comment by cxw42** [comment]
Thanks for reporting!  I just realized this is a duplicate of #224 :)
