### ISSUE TITLE
Enable discussions feature in github?

### ISSUE THREAD

**Issue by wrgrant** [cxw42/TabFern#241]
Maybe issues are the place for discussion, maybe not?

I saw your note on the tab-at-a-time release about giving you feedback. But I don't know how I would do that other than create an issue, which then muddies up the issue tracker with non-issue topics.

**Comment by cxw42** [comment]
Thanks for the suggestion --- I wasn't aware of that feature!  Could you point me to a repo in which you have had a positive experience with Discussions so I can see an example of how it's being used?

At the moment, opening issues is fine, since that's the only choice :) .

**Comment by wrgrant** [comment]
Sure, here is one I'm aware of.

https://github.com/johannesjo/super-productivity/discussions

My feedback was just that the alpha of 0.3 works great and I'm looking forward to when it gets pushed to the main branch 😁

**Comment by cxw42** [comment]
Worth a shot --- done!  I am keeping feature requests in the Issues for now.  Thanks for the suggestion, and for supporting TF!  (And, to make a shameless request, would you be willing to star TF? ;)  Thank you for considering this request!)
