### ISSUE TITLE
[Update Readme] How this is any different from Tab outliner? readme doesn't inform!

### ISSUE THREAD

**Issue by Droyk** [cxw42/TabFern#284]
There should be a section that says what are the key diff. b/w the tab fern & tab outliner? both in the extension store & readme section. It should clearly say why would a user want to jump to tab fern when they are already using tab outliner? why did you make it? 
when tab outliner is already great & working? what do you want to achieve? 
What are its key advantages over tab outliner?

**Comment by cxw42** [comment]
@Droyk thanks for the suggestion --- that's an interesting idea!  To answer one of your questions, I started writing TF when a Chrome update broke TO and I realized that my workload depended on a tab organizer :) .

**Comment by Droyk** [comment]
> @Droyk thanks for the suggestion --- that's an interesting idea! To answer one of your questions, I started writing TF when a Chrome update broke TO and I realized that my workload depended on a tab organizer :).

such a vague reply mate. I still don't understand why should I be using this extension when a good working extension already exists! what is wrong with that one! how your extension is different? please tell me why should I or anyone who uses TO religiously jump to this project? what kind of advantages does it offer compared to TO?
>that's an interesting idea! 

You're mistaken about this. it isn't a great idea! this should've been your very first thought! why I'm gonna make this? what TO doesn't have? why an old user of TO's want to transition to TF? what is this alternative wants to achieve?

you said chrome update broke TO pretty sure must have happened seems to happen to me almost every quarter or 2 but that's why I have daily backups so why should I start using TF? & it's not like TO isn't being updated last I checked it updated like 9 months ago. Dev only gives updates annually I'm okay with it. it has too many users for the dev. to abandon it! 

You said "TO" broke after a chrome update. well, the same will happen with your extension something will break it too? So Why Should I start using your extension when I already know that there is a 100% chance that the same will break this tooo.

**Comment by Droyk** [comment]
did you make this extension to see if you can make it possible? to prove this to yourself? if it is then that's great. but should mention that on the chrome extension page!

**Comment by LeeBreisacher** [comment]
My 2 cents...  There is a huge gaping problem with TO: The creator has completely abandoned it as far as I can tell. There have been no updates for years, they never answer questions or problems. There have been requests to make the source available so others could take over ownership, no response. TBH, I continue to use TO (because, frankly, I have not had time to try out TF for real, and I get the sense it is not complete enough, functionality-wise?), but I live in fear that some Chrome update is going to break TO for everyone and the creator will be nowhere, then suddenly we're all screwed. That's why TF (or similar) is so important.

**Comment by Droyk** [comment]
> My 2 cents... There is a huge gaping problem with TO: The creator has completely abandoned it as far as I can tell. There have been no updates for years.

the last update was on [April 7, 2021](https://chrome.google.com/webstore/detail/tabs-outliner/eggkanocgddhmamlbiijnphhppkpkmkl?hl=en) doesn't really seem like abandoned for years to me but I can relate update needs to be a bit quicker. he usually updates it annually.

>they never answer questions or problems.

This is true yes, the dev hardly answers any!

> but I live in fear that some Chrome update is going to break TO for everyone and the creator will be nowhere, then suddenly we're all screwed. That's why TF (or similar) is so important.

Okay that's should've been mentioned I get it an active open-sourced alternative to Tab outliner seems great to me. but @cxw42 should mention it on the top of the readme & chrome extension page of what it actually is
"Since it is so similar to Tab outliner the only thing this alternative is good at is being in active development and being open source. right now it doesn't offer any other great functionalities that don't already come with TO! but it will in the coming future!
so keep watching!

**Comment by Droyk** [comment]
@LeeBreisacher in contrast to yours @cxw42 reply felt incomplete. I just wanted to know why should I need to transition to this!
Thank you for enlightenment I guess!

**Comment by wrgrant** [comment]
@Droyk your initial idea is good, but your follow up comments are incredibly rude and demanding for an open source project. English may not be your first language, but take some notes on the pushback you are getting here.

> I just wanted to know why should I need to transition to this!

You don't. Do whatever you want.

This book may change your life: "How to win friends and influence people" by Dale Carnegie.

If you truly see the market desperate for this information, I would suggest you exercise TF fully, and create your own blog post or youtube video on why one would jump from TO.
Put in some effort where you see information missing.

This is a side project by a dude who is clearly busy with real life (as is TO it seems). How about sending @cxw42 a thanks for creating a viable alternative to what clearly is a necessary piece of software for you?
