### ISSUE TITLE
Move tabs between windows via the TabFern window

### ISSUE THREAD

**Issue by cxw42** [cxw42/TabFern#36]
Including moving closed tabs between windows.  Requested by Blank Makkara via user review 2017/09/07.

I would also add the ability to create a new window - e.g., drag a tab's node out of the tree to create a new window to hold that tab (open window for open tabs; closed window for closed tabs).

**Comment by bluikko** [comment]
It would be great - similar to the "drag'n'drop windows" feature in 0.1.6 (which is working fine) but for individual tabs.

**Comment by cxw42** [comment]
@bluikko Thanks for the test report on drag-and-drop!  How does the importance of this (#36) compare to #34 and #35 in your use of TabFern?  That will affect how I go about the implementation.

**Comment by bluikko** [comment]
To me #34 would not be important. It is mostly cosmetic and helps to visualize which tabs go together but #35 would be actually useful.

There are several ways to implement #35 and one way could be: a closed tab could be drag'n'dropped out from a closed window, either to an already open window or to outside any existing window thus creating a new window with only the one tab. I guess the other way would be to somehow open only one tab in a window, keeping the other tabs in "closed" state in the TabFern outline... I do not know which one would be easier to use. The former would seem easier to implement at least but I can't imagine if it would be more cumbersome to use - perhaps someone else has some opinions about this also?

**Comment by cxw42** [comment]
@bluikko I just at-mentioned you in #37 - I am curious to hear your thoughts there.  Did you get a GitHub notification in that issue?  I suspect you probably did, but I would like to confirm.  Thanks!  (I will delete this comment after you respond)

**Comment by cxw42** [comment]
I am testing 231366c for inclusion in v0.1.8 --- that has drag-and-drop between closed windows.  Drag-and-drop rearrangement within and between open windows will follow later, as will drag-and-drop between open and closed windows.

**Comment by bluikko** [comment]
Seems to work just fine between open windows. I could not find any bugs so far.

**Comment by cxw42** [comment]
@bluikko, are you able to test unpacked extensions?  The `/tabfern` tree in 8fdf0be has full tab dragging and is ready for testing.  If not, would you be willing to try out a test version if I put it in the Chrome Web Store under a different name?  Either way, you would have to manually backup and import your save data, but you could run both at once.

**Comment by cxw42** [comment]
This has been in production now for a week or so, and I haven't heard any complaints.  Therefore, I am marking this one as for the history books!  Please reopen if you have any issues.

**Comment by bluikko** [comment]
I have tried using it several times to re-organize tabs to windows and did not notice any issues so far.
