### ISSUE TITLE
User option to turn off H scrollbar

### ISSUE THREAD

**Issue by cxw42** [cxw42/TabFern#38]
@r4j4h Would you be willing to look at this one?  Add a user option to control whether the TabFern window has a horizontal scrollbar or not.  Requested by Blank Makkara via user review 2017/09/07.

Also related to #31.

**Comment by r4j4h** [comment]
This sounds good! Though until #31 is solved I think the "stick-to-the-right" functionality needs to disable as well or else it goes offscreen. What do you think?

**Comment by cxw42** [comment]
I believe it should be possible to handle both of these issues at once.  At the very least, the current hack with [`vscroll_function`](https://github.com/cxw42/TabFern/blob/master/src/view/view.js#L328) is basically functional.  I do hope there's a cleaner way, but if not, could we just change `overflow` based on a user option, and leave `position: fixed` + `vscroll_function` in place?

**Comment by r4j4h** [comment]
Yeah, I was thinking add an option, depending on that option add an additional class that adds `overflow-x: hidden` for the user request.

Without changing jstree styles or DOM ordering as is your vscroll function sounds good to me!

**Comment by cxw42** [comment]
Cool :) .  Would you please add a commit for this to the #31 branch as you have opportunity?  I will then merge to take care of both at once.  Thank you!
