### ISSUE TITLE
(Reopened) Open windows are duplicated after Chrome restart

### ISSUE THREAD

**Issue by bluikko** [cxw42/TabFern#41]
If Chrome is restarted due to an update (regardless of setting "Pages to open on startup" that is set to "Open the New Tab page"), Chrome helpfully re-opens the windows that were open before restart.

But TabFern then naturally creates duplicate windows for all the windows that were re-opened by Chrome.

Could it perhaps be possible to test if a window has exactly same tabs than already existing window in TabFern and then not create a new window with the same tabs as before?
I'm not sure if there's a way to test if Chrome was just restarted, but if there is then it might be even better to take that too into account when checking whether to re-use the old windows in TabFern instead of creating new ones.

Currently after Chrome restart the easiest option is to delete all windows that were open before the restart and rename the newly created windows back to the same names as the windows before restart.

**Comment by cxw42** [comment]
@bluikko thanks for testing TabFern, and thanks for reporting!  I have a similar experience sometimes when I refresh the TabFern window during debugging.

This is related to #23, and I would like to handle these two issues together.  I will put this next on my worklist - I am presently working on [Chrome 61 stuff](https://bugs.chromium.org/p/chromium/issues/detail?id=762951) and drag-and-drop rearranging of windows in the tree :) .  Please continue to submit issues as you encounter them during testing!

**Comment by cxw42** [comment]
@bluikko Are you by any chance comfortable [loading unpacked extensions in developer mode](https://stackoverflow.com/a/24577660/2877364)?  If so, you can test this in [branch v017pre1](https://github.com/cxw42/TabFern/tree/v017pre1).  If not, it will be included in the 0.1.7 update in a few days once I have had more of a chance to test it :) .

**Comment by cxw42** [comment]
I have fixed some of the cases, but still am working on others.  I am presently refactoring to get a better handle on things, including this issue but in the crash-recovery situation.

Do you happen to know any way to force an update so I could test my code?  I do not, and my Chrome installation updates silently.

**Comment by cxw42** [comment]
Reopened to work on a more robust version

**Comment by bluikko** [comment]
This seems to be fixed now?

After I gave names to my currently open windows & restarted Chrome for updates, the existing windows were re-opened and kept the old names in TabFern - the open windows did not get duplicated to "Unsaved".

**Comment by cxw42** [comment]
Thanks for the report - glad to hear the update case is fixed!  I will leave this open to work on crash recovery.

**Comment by cxw42** [comment]
@bluikko based on your comment in #55, it sounds like this is fixed.  I will close this issue and respond over there.  Thanks for the feedback!
