### ISSUE TITLE
Current active tab highlight (bold text) lost in outline after active tab drag-drop moved

### ISSUE THREAD

**Issue by bluikko** [cxw42/TabFern#61]
The new functionality of moving tabs within a window by drag'n'drop works fine. But there's a small bug:
if currently active tab (highlighted in bold text) is moved by drag'n'drop, the bold text is lost and does not recover after focus is returned to the active window.

More precisely:
If focus is moved to TabFern window, the active tab highlight (bold text) is lost, which is understandable.
But after focus is returned from TabFern window to Chrome (back to the tab that was active before clicking at TabFern window), the active tab highlight does not return, only the active window is highlighted with bold text.

It recovers after some other tab is activated.

**Comment by cxw42** [comment]
Related to #42.  Thanks for the report!
