### ISSUE TITLE
Option to show the tree connections

### ISSUE THREAD

**Issue by cxw42** [cxw42/TabFern#65]
Show the vertical/horizontal lines.
Requested by LateNightHacks via user review 2017/10/14.

**Comment by ShervinM** [comment]
Sweeet!
btw, I can do some graphics for you, I'm not a pro artist but can find my way around photoshop and illustrator. I can make backgrounds and icons and similar stuff. for example the link lines could use an upgrade :)

**Comment by cxw42** [comment]
@ShervinM Thanks for your comments on this and other issues!  I will work through them :) .

Always a pleasure to meet a graphician! ;)  Yes, I would certainly appreciate help with the visual assets.  Specifically, the link lines and arrows are [here](https://github.com/vakata/jstree/blob/master/dist/themes/default-dark/32px.png).  If you would like to have a crack at improvements, please feel free to edit --- just make sure the sizes and positions stay the same and the lines start and end in the same places.  That way it should be a drop-in change.  In that file, TabFern currently uses the lines and triangles for the grid, the folder for the closed-window icon, and the X and checkmark for drag-and-drop operations.  I don't use the other icons yet.

Are you familiar with [loading unpacked extensions](https://stackoverflow.com/a/24577660/2877364)?  That is the best way I know of to try out changes to the images.  Clone this repo and load `/tabfern` as an unpacked extension.  Then you can change or replace `/tabfern/assets/jstree-3.3.4/themes/default-dark/32px.png` and hit Shift+F5 in the TabFern window to reload.

Feel free to ping me if you have questions, or open a pull request if you have something ready to go live.  Thank you very much for participating!

**Comment by cxw42** [comment]
@ShervinM Not sure if you got the notification on #137 - another designer has offered to work on an icon, in case you have any ideas or would like to discuss.  Hope all is going well!
