### ISSUE TITLE
Narrower or hidden vertical scrollbar

### ISSUE THREAD

**Issue by cxw42** [cxw42/TabFern#68]
> is it possible to make the scrollbar even narrower? (or just not show it at all while still keeping the page scrollable?)

What is your preference for a way of scrolling when the scrollbar is hidden?  I tried an easy test: `$('#tree-iframe html') overflow-y: hidden`.  Unfortunately, besides hiding the scrollbar, that disabled mouse-wheel and middle-click+move scrolling on my test system.

Requested by LateNightHacks via user review 2017/10/14.

**Edit** Looks like narrow should be fairly straightforward -- see [here](https://github.com/mikethedj4/Webkit-Scrollbar-Generator)

**Comment by ShervinM** [comment]
hmmm, yeah, nope, mouse scroll is my everything :D 
seems TO uses a custom scrollbar?
yep, something like Scrollbar-Generator looks like the right apprach
