### ISSUE TITLE
Red X to close tab

### ISSUE THREAD

**Issue by BugZappr** [cxw42/TabFern#93]
This is a real common feature, and would enhance the usefulness of TabFern considerably.  Most of these vertical tab applications have a red x that shows up, usually at the extreme right, when you hover over a tab that you can click to close the individual tab.  It also sounds like a likely context menu item.  TF could really use this.  Sometimes, when too many tabs are open, and I have the window more narrow than my screen to make room for TF, I don't even get to see the tab for my current page on the tab bar.

**Comment by cxw42** [comment]
Based on your other comments, I think you mean an X to both close the tab and remove the tab from the list in the TabFern window.  Am I understand correctly?  Closing the tab but keeping it in the list is part of #36.

**Comment by BugZappr** [comment]
I must admit that I have been trying to use TabFern as a bar that exactly mirrors the open tabs, as if it were the lost vertical tab bar in Chrome.  Having your active tabs not exactly mirror your unsaved tabs, to me seems nothing but a source of confusion (as well as not having the active tab scrolled to), so yes, my instinct is to mirror the closing of a TabFern tab with the closing of the real tab.

**Comment by ShervinM** [comment]
@BugZappr have you used Tabs Outliner at all? this extension is much closer to that than to various vertical tabs list extensions. both Tabs Outliner and Tab Fern are considerably more capable extensions mainly used by people that do extensive reading or research online. aside from basic saving and backup it allows you to organise huge number of tabs while allowing for and maintaining a hierarchy of tabs and thereby a track of the path taken. loading/unloading of tabs and windows on the fly also lets users manage memory and resource usage.

I suppose @cxw42 could include an option to disable all management features and turn it to a basic vertical tab bar, but then might as well strip some of the code and release a lighter extension for tab bar replacement, which would be quite neat actually

**Comment by BugZappr** [comment]
I do extensive reading online, but find bookmarks sufficient for hierarchically organizing my links.  I find Tabs Outliner to be even worse than TabFern about creating top-level entries with all the tabs from my previous session.  It's also crippleware and not open source.

I think a hierarchy of path taken can be consistent with a strict one-to-one relationship of "Unsaved Tabs" matching the order that the tabs occur in.  In that case, they would just jump up a level or more if dragged to a new position in the browser's toolbar, e.g.  I'm using The Great Discarder to manage my discarding chores, but I can see how others would want finer-grain control.

As to a stripped-down version, I would be for that too; but then some users might prefer to disable the management features for one session of Web surfing, and then re-enable them a little later.  Hence, I'd lean toward a single version, and a single version that had open tabs in a strict order that matches the browser; although I take it that ShervinM and others would prefer not to do it that way.

The most involved, but complete way of doing it would be to have one option to have a new, top-level tree which represented the tabs in the exact order as open in the browser.  Then, there would be another to only show this tree as a flat vertical tab bar.  Then, suppose somebody is using it as a vertical tab bar, they might then go back to the tree view, and save some tabs.  Then, they could look in "Unsaved" and see what is saved and what isn't, and still see the tabs in the same order as the browser in another top-level entry.  Finally, I'd have an option to disable recovering tabs at all.  I have Tabs Backup & Restore for that; and it would keep it from littering up the menu with ever more recovered tabs entries, just because I exit Iron and restart it.

You have a very complex plugin that duplicates some functionality that other plugins do perfectly well: unloading tabs ("discarding" in Chrome parlance being the important function here), and backing them up.  There's no reason TabFern shouldn't do all this, but it would also help TabFern to be able to turn off such functions, and play well with other plugins that someone might want to do those functions instead.  That way, its functionality can be more modular, if desired.

**Comment by cxw42** [comment]
I'm going to keep this issue as just the red X.  

I will think about the more general use case.  The easiest implementation would probably be a separate window you can choose to open that just lists tabs for a particular Chrome window.
