### ISSUE TITLE
Intermittent "Recovered Tabs" showing up when just closing and reopening browser & TF

### ISSUE THREAD

**Issue by BugZappr** [cxw42/TabFern#96]
I'd like to use TabFern as just a replacement for the Tab Bar.  I have Chrome (really Iron) set in Startup to Continue where I left off.  Sometimes, I get a just a "Recovered Tabs" entry in TF, consisting of just my open tabs.  It would seem more logical if it were still named "Unsaved Tabs" on closing my browser and reopening it, since that's what it read before 'continuing where I left off'.  I wouldn't complain, if that were the only issue, however.

Occasionally, but inexorably, I get additional "Recovered Tabs" entries in addition to my current "Unsaved Tabs" top level entries - to the effect that I have these extra "Recovered Tabs" entries that keep eventually building up, which I must then delete.  I don't really need TF to recover _any_ tabs for me, given how I use Iron.  There are separate tab backup plugins, and between them and continuing where I left off, they can handle my tab recovery chores just fine.  To me, this is unnecessary functionality that just creates a minor annoyance and uses up some memory.  If tab recovery is the game, then why not have a timed backup option, and make a fully featured one?  In any case, it should be optional, IMHO.

**Comment by cxw42** [comment]
This happens for me fairly regularly when I:

 - open a window with only the TabFern settings page
 - close the TabFern window (red "X" on Windows)
 - reopen the TabFern window by clicking the TabFern button in the browser toolbar.

The same thing seems to have happened to @bluikko in #89.

It does not seem to happen as regularly for me with other URLs, curiously.

**Comment by BugZappr** [comment]
FWIW: I'm running Iron browser vers. 62.0.3250.0 on Win7 sp1, 32-bit.

**Comment by cxw42** [comment]
@BugZappr Is this fixed for you in v0.1.15?

**Comment by BugZappr** [comment]
It seems to be.  I've played around with it for about an hour, closing TF, then the browser first, and vice versa.  I'll let you know if I see it again.  As I remember, it was sorta intermittent.

**Comment by cxw42** [comment]
@BugZappr thanks!  I will close as you suggest; please do reply if the problem recurs.
