### ISSUE TITLE
Option to change the colour of the narrow scrollbar

### ISSUE THREAD

**Issue by ShervinM** [cxw42/TabFern#97]
The narrow scrollbar looks AWESOME, now much better than TO I would say, just a minor nitpick, the yellow looks a bit "in the face", would be awesome if we could customize the bar and it's background. it would blend much better with the rest. thanks!

**Comment by cxw42** [comment]
@ShervinM run unpacked if you can't wait ;)

**Comment by ShervinM** [comment]
haha, it's alright
I like to use TF as my daily driver but it still lacks a few things I rely on heavily. individual tab load/unload is the biggest one.
